# ShopSmart E-Commerce Machine Learning Lab

In [ ]:
# STEP 1: IMPORT LIBRARIES

# Pandas is used for reading and manipulating datasets
import pandas as pd

# NumPy helps with numerical computations
import numpy as np

# Machine Learning Algorithms
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

# Used to split dataset into training and testing data
from sklearn.model_selection import train_test_split

# Used to evaluate classification models
from sklearn.metrics import accuracy_score, confusion_matrix

# Converts text columns into numerical values
from sklearn.preprocessing import LabelEncoder

In [ ]:
# STEP 2: LOAD DATASET

df = pd.read_csv('ShopSmart_Customers.csv')

# Display first 5 rows
df.head()

,CustomerID,Age,Gender,Income,ProductsViewed,CartItems,TimeOnSite,PreviousPurchases,DiscountUsed,Membership,FavoriteCategory,Purchased,AmountSpent
0,1,20,Male,24114,39,7,19,11,30,Silver,Books,1,7514
1,2,57,Female,84965,40,5,37,25,3,Silver,Books,1,10648
2,3,51,Male,56321,17,9,39,3,22,Platinum,Books,1,9002
3,4,57,Male,93297,37,2,21,25,1,Silver,Fashion,1,8881
4,5,44,Male,116652,39,2,8,7,21,Silver,Home,1,7116

In [ ]:
# STEP 3: UNDERSTAND THE DATASET

print('Shape:', df.shape)
print('\nColumns:')
print(df.columns)

print('\nData Types')
print(df.dtypes)

Shape: (500, 13)

Columns:
Index(['CustomerID', 'Age', 'Gender', 'Income', 'ProductsViewed', 'CartItems',
       'TimeOnSite', 'PreviousPurchases', 'DiscountUsed', 'Membership',
       'FavoriteCategory', 'Purchased', 'AmountSpent'],
      dtype='object')

Data Types
CustomerID            int64
Age                   int64
Gender               object
Income                int64
ProductsViewed        int64
CartItems             int64
TimeOnSite            int64
PreviousPurchases     int64
DiscountUsed          int64
Membership           object
FavoriteCategory     object
Purchased             int64
AmountSpent           int64
dtype: object

In [ ]:
# STEP 4: SUMMARY STATISTICS

df.describe()

,CustomerID,Age,Income,ProductsViewed,CartItems,TimeOnSite,PreviousPurchases,DiscountUsed,Purchased,AmountSpent
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.00000,500.000000
mean,250.500000,41.428000,87556.388000,25.460000,4.356000,29.830000,14.852000,19.06800,0.95800,8558.034000
std,144.481833,13.569565,37710.299661,13.825291,2.824397,16.651115,8.638712,11.55571,0.20079,3224.867606
min,1.000000,18.000000,20207.000000,1.000000,0.000000,1.000000,0.000000,0.00000,0.00000,0.000000
25%,125.750000,29.750000,54571.250000,14.000000,2.000000,16.000000,7.000000,9.00000,1.00000,6730.750000
50%,250.500000,42.000000,88597.500000,24.500000,4.000000,30.000000,15.000000,19.00000,1.00000,8779.500000
75%,375.250000,53.000000,120186.750000,37.000000,7.000000,44.000000,22.250000,28.25000,1.00000,10704.500000
max,500.000000,64.000000,149992.000000,49.000000,9.000000,59.000000,29.000000,39.00000,1.00000,16326.000000

In [ ]:
# STEP 5: BUSINESS QUESTIONS

# Total customers
print('Customers:', len(df))

# Total purchasers
print('Purchased:', df['Purchased'].sum())

# Average spending
print('Average Spending:', round(df['AmountSpent'].mean(),2))

# Highest spender
print('\nHighest Spender')
print(df.loc[df['AmountSpent'].idxmax()])

Customers: 500
Purchased: 479
Average Spending: 8558.03

Highest Spender
CustomerID              281
Age                      62
Gender               Female
Income               145654
ProductsViewed            4
CartItems                 9
TimeOnSite                9
PreviousPurchases        28
DiscountUsed              9
Membership             Gold
FavoriteCategory      Books
Purchased                 1
AmountSpent           16326
Name: 280, dtype: object

In [ ]:
# STEP 6: PREPARE DATA

# Machine learning algorithms require numbers.
# Membership and FavoriteCategory contain text.

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['Membership'] = le.fit_transform(df['Membership'])
df['FavoriteCategory'] = le.fit_transform(df['FavoriteCategory'])

In [ ]:
# STEP 7: DECISION TREE

# Business Question:
# Will customer purchase?

X = df.drop(['CustomerID','Purchased','AmountSpent'], axis=1)

y = df['Purchased']

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train,y_train)

pred = dt.predict(X_test)

print('Decision Tree Accuracy:', accuracy_score(y_test,pred))

print('\nConfusion Matrix')
print(confusion_matrix(y_test,pred))

Decision Tree Accuracy: 0.96

Confusion Matrix
[[ 3  2]
 [ 2 93]]

In [ ]:
# Predict purchase for a new customer

new_customer = [[30,1,60000,20,3,15,5,10,1,2]]

print('Purchase Prediction:', dt.predict(new_customer)[0])

Purchase Prediction: 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
# STEP 8: KNN

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)

knn_pred = knn.predict(X_test)

print('KNN Accuracy:', accuracy_score(y_test,knn_pred))

KNN Accuracy: 0.95

In [ ]:
# STEP 9: LINEAR REGRESSION

X_reg = df.drop(['CustomerID','Purchased','AmountSpent'], axis=1)

y_reg = df['AmountSpent']

X_train_reg,X_test_reg,y_train_reg,y_test_reg = train_test_split(
    X_reg,y_reg,test_size=0.2,random_state=42
)

lr = LinearRegression()

lr.fit(X_train_reg,y_train_reg)

amount = lr.predict([[30,1,60000,20,3,15,5,10,1,2]])

print('Predicted Spending:', amount[0])

Predicted Spending: 4477.686668606446

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

## Student Tasks (10 Questions)

1. How many customers are present?
2. How many customers purchased?
3. What is the average income?
4. What is the average amount spent?
5. Which customer spent the most?
6. Build a Decision Tree and report accuracy.
7. Build a KNN model and report accuracy.
8. Which model performed better?
9. Predict purchase for a new customer.
10. Predict spending amount for the same customer.

### Challenge Questions

11. Which membership level spends the most?
12. Which product category is most popular?
13. Does discount influence purchases?
14. Which feature appears most important?
15. Suggest one business action based on your findings.

In [ ]:
print("Total Customers:", len(df))

Total Customers: 500

In [ ]:
print("Customers Who Purchased:", df['Purchased'].sum())

Customers Who Purchased: 479

In [ ]:
df['Purchased'].value_counts()

Purchased
1    479
0     21
Name: count, dtype: int64

In [ ]:
print("Average Income:", df['Income'].mean())

Average Income: 87556.388

In [ ]:
print("Average Amount Spent:", df['AmountSpent'].mean())

Average Amount Spent: 8558.034

In [ ]:
highest_spender = df.loc[df['AmountSpent'].idxmax()]

print(highest_spender)

CustomerID              281
Age                      62
Gender                    0
Income               145654
ProductsViewed            4
CartItems                 9
TimeOnSite                9
PreviousPurchases        28
DiscountUsed              9
Membership                0
FavoriteCategory          0
Purchased                 1
AmountSpent           16326
Name: 280, dtype: int64

In [ ]:
df.nlargest(1,'AmountSpent')

,CustomerID,Age,Gender,Income,ProductsViewed,CartItems,TimeOnSite,PreviousPurchases,DiscountUsed,Membership,FavoriteCategory,Purchased,AmountSpent
280,281,62,0,145654,4,9,9,28,9,0,0,1,16326

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = df.drop(['CustomerID','Purchased','AmountSpent'], axis=1)

y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

pred = dt.predict(X_test)

print("Decision Tree Accuracy:",
      accuracy_score(y_test,pred))

Decision Tree Accuracy: 0.96

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)

knn_pred = knn.predict(X_test)

print("KNN Accuracy:",
      accuracy_score(y_test,knn_pred))

KNN Accuracy: 0.95

In [ ]:
dt_acc = accuracy_score(y_test,pred)

knn_acc = accuracy_score(y_test,knn_pred)

print("Decision Tree:",dt_acc)
print("KNN:",knn_acc)

if dt_acc > knn_acc:
    print("Decision Tree performed better")
else:
    print("KNN performed better")

Decision Tree: 0.96
KNN: 0.95
Decision Tree performed better

In [ ]:
new_customer = [[
    30,      # Age
    1,       # Gender
    60000,   # Income
    20,      # Products Viewed
    3,       # Cart Items
    15,      # Time On Site
    5,       # Previous Purchases
    10,      # Discount Used
    1,       # Membership
    2        # Favorite Category
]]

prediction = dt.predict(new_customer)

print("Purchase Prediction:",
      prediction[0])

Purchase Prediction: 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
amount_prediction = lr.predict(new_customer)

print("Predicted Spending Amount:",
      amount_prediction[0])

Predicted Spending Amount: 4477.686668606446

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(